-- Seed books from Goodreads CSV export
-- Run this AFTER schema.sql in the Supabase SQL Editor

insert into books (title, author, shelf, date_read, user_id) values
('The Housemaid''s Secret', 'Freida McFadden', 'read', 'Feb 27, 2026', 'her'),
('Finlay Donovan Is Killing It', 'Elle Cosimano', 'read', 'Feb 22, 2026', 'her'),
('The Push', 'Ashley Audrain', 'read', 'Feb 09, 2026', 'her'),
('Vera Wong''s Guide to Snooping [On a Dead Man]', 'Jesse Q. Sutanto', 'read', 'Feb 06, 2026', 'her'),
('Life''s Too Short', 'Abby Jimenez', 'read', 'Jan 25, 2026', 'her'),
('The Housemaid', 'Freida McFadden', 'read', 'Jan 29, 2026', 'her'),
('Atmosphere', 'Taylor Jenkins Reid', 'read', 'Jan 09, 2026', 'her'),
('The Happy Ever After Playlist', 'Abby Jimenez', 'read', 'Jan 06, 2026', 'her'),
('The Friend Zone', 'Abby Jimenez', 'read', 'Dec 10, 2025', 'her'),
('Watching You', 'Lisa Jewell', 'currently-reading', null, 'her'),
('The Retirement Plan', 'Sue Hincenbergs', 'read', 'Oct 26, 2025', 'her'),
('Don''t Let Him In', 'Lisa Jewell', 'read', 'Oct 13, 2025', 'her'),
('The World Outside My Window', 'Clare Swatman', 'read', 'Sep 05, 2025', 'her'),
('Then She Was Gone', 'Lisa Jewell', 'read', 'Aug 12, 2025', 'her'),
('The Five-Star Weekend', 'Elin Hilderbrand', 'read', 'Aug 09, 2025', 'her'),
('The Mindf*ck Series', 'S.T. Abby', 'to-read', null, 'her'),
('Margo''s Got Money Troubles', 'Rufi Thorpe', 'read', 'Jul 08, 2025', 'her'),
('Vera Wong''s Unsolicited Advice for Murderers', 'Jesse Q. Sutanto', 'read', 'Jul 2025', 'her'),
('Sweet Bean Paste', 'Durian Sukegawa', 'read', 'Apr 11, 2025', 'her'),
('I''m Starting to Worry About This Black Box of Doom', 'Jason Pargin', 'dnf', null, 'her'),
('Norwegian Wood', 'Haruki Murakami', 'to-read', null, 'her'),
('Onyx Storm', 'Rebecca Yarros', 'read', 'Mar 16, 2025', 'her'),
('Impossible Creatures', 'Katherine Rundell', 'to-read', null, 'her'),
('The Art Thief', 'Michael Finkel', 'to-read', null, 'her'),
('Astor: The Rise and Fall of an American Fortune', 'Anderson Cooper', 'to-read', null, 'her'),
('The Radium Girls', 'Kate Moore', 'to-read', null, 'her'),
('Check & Mate', 'Ali Hazelwood', 'to-read', null, 'her'),
('Things We Left Behind', 'Lucy Score', 'to-read', null, 'her'),
('Things We Never Got Over', 'Lucy Score', 'to-read', null, 'her'),
('The Seven Year Slip', 'Ashley Poston', 'to-read', null, 'her'),
('Love, Theoretically', 'Ali Hazelwood', 'to-read', null, 'her'),
('Babel', 'R.F. Kuang', 'currently-reading', null, 'her'),
('Before the Coffee Gets Cold', 'Toshikazu Kawaguchi', 'to-read', null, 'her'),
('Rock Paper Scissors', 'Alice Feeney', 'to-read', null, 'her'),
('The Silent Patient', 'Alex Michaelides', 'to-read', null, 'her'),
('Good Material', 'Dolly Alderton', 'to-read', null, 'her'),
('Hello Beautiful', 'Ann Napolitano', 'to-read', null, 'her'),
('Tom Lake', 'Ann Patchett', 'to-read', null, 'her'),
('Yours Truly', 'Abby Jimenez', 'read', 'Dec 10, 2024', 'her'),
('Part of Your World', 'Abby Jimenez', 'read', 'Nov 23, 2024', 'her'),
('The God of the Woods', 'Liz Moore', 'read', 'Nov 30, 2024', 'her'),
('The Bookstore Wedding', 'Alice Hoffman', 'to-read', null, 'her'),
('The Bookstore Sisters', 'Alice Hoffman', 'to-read', null, 'her'),
('The Frozen River', 'Ariel Lawhon', 'read', 'Jun 19, 2025', 'her'),
('Real Americans', 'Rachel Khong', 'to-read', null, 'her'),
('Just for the Summer', 'Abby Jimenez', 'read', 'Apr 14, 2025', 'her'),
('The Secret History', 'Donna Tartt', 'to-read', null, 'her'),
('The Wedding People', 'Alison Espach', 'read', 'Jan 03, 2025', 'her'),
('Blue Sisters', 'Coco Mellors', 'read', 'Aug 28, 2025', 'her'),
('First Lie Wins', 'Ashley Elston', 'to-read', null, 'her'),
('Ask for Andrea', 'Noelle W. Ihli', 'to-read', null, 'her'),
('The Grace Year', 'Kim Liggett', 'to-read', null, 'her'),
('More Days at the Morisaki Bookshop', 'Satoshi Yagisawa', 'read', 'Dec 05, 2024', 'her'),
('I Hope This Doesn''t Find You', 'Ann Liang', 'to-read', null, 'her'),
('Fangirl Down', 'Tessa Bailey', 'to-read', null, 'her'),
('The Rom-Commers', 'Katherine Center', 'to-read', null, 'her'),
('Somewhere Beyond the Sea', 'T.J. Klune', 'read', 'May 19, 2025', 'her'),
('Not in Love', 'Ali Hazelwood', 'read', 'Jul 13, 2025', 'her'),
('Funny Story', 'Emily Henry', 'to-read', null, 'her'),
('Bride', 'Ali Hazelwood', 'read', 'Aug 05, 2025', 'her'),
('Emily Wilde''s Compendium of Lost Tales', 'Heather Fawcett', 'to-read', null, 'her'),
('Emily Wilde''s Map of the Otherlands', 'Heather Fawcett', 'currently-reading', null, 'her'),
('The Authenticity Project', 'Clare Pooley', 'to-read', null, 'her'),
('Sometimes I Lie', 'Alice Feeney', 'to-read', null, 'her'),
('The House in the Cerulean Sea', 'T.J. Klune', 'read', 'Sep 18, 2024', 'her'),
('Legends & Lattes', 'Travis Baldree', 'currently-reading', null, 'her'),
('Emily Wilde''s Encyclopaedia of Faeries', 'Heather Fawcett', 'read', 'Dec 24, 2024', 'her'),
('Conversations with Friends', 'Sally Rooney', 'to-read', null, 'her'),
('Normal People', 'Sally Rooney', 'to-read', null, 'her'),
('The Very Secret Society of Irregular Witches', 'Sangu Mandanna', 'read', 'Jan 16, 2026', 'her'),
('Goodbye Days', 'Jeff Zentner', 'to-read', null, 'her'),
('Days at the Morisaki Bookshop', 'Satoshi Yagisawa', 'read', 'Sep 2024', 'her'),
('The Number One Ladies'' Detective Agency', 'Alexander McCall Smith', 'read', 'Aug 30, 2024', 'her'),
('The Graham Effect', 'Elle Kennedy', 'read', 'Aug 09, 2024', 'her'),
('Circe', 'Madeline Miller', 'currently-reading', null, 'her'),
('Beach Read', 'Emily Henry', 'read', 'Apr 11, 2024', 'her'),
('Happy Place', 'Emily Henry', 'read', 'Mar 23, 2024', 'her'),
('Shark Heart', 'Emily Habeck', 'to-read', null, 'her'),
('Iron Flame', 'Rebecca Yarros', 'read', 'Mar 31, 2024', 'her'),
('The Lying Game', 'Ruth Ware', 'read', 'Mar 21, 2024', 'her'),
('Fourth Wing', 'Rebecca Yarros', 'read', 'Feb 03, 2024', 'her'),
('The Guest List', 'Lucy Foley', 'read', 'Aug 20, 2024', 'her'),
('I''ll Be Gone in the Dark', 'Michelle McNamara', 'read', 'Jan 27, 2024', 'her'),
('The Psychopath Test', 'Jon Ronson', 'paused', null, 'her'),
('The Man Who Mistook His Wife for a Hat', 'Oliver Sacks', 'paused', null, 'her'),
('Mister Magic', 'Kiersten White', 'read', 'Nov 04, 2023', 'her'),
('The Curious Charms of Arthur Pepper', 'Phaedra Patrick', 'paused', null, 'her'),
('The Hawthorne Legacy', 'Jennifer Lynn Barnes', 'to-read', null, 'her'),
('Fevre Dream', 'George R.R. Martin', 'paused', null, 'her'),
('The Couple Next Door', 'Shari Lapena', 'read', 'Sep 16, 2023', 'her'),
('Morbidly Yours', 'Ivy Fairbanks', 'to-read', null, 'her'),
('Harry Potter and the Cursed Child', 'J.K. Rowling', 'to-read', null, 'her'),
('None of This Is True', 'Lisa Jewell', 'read', 'Sep 26, 2023', 'her'),
('The Nightingale', 'Kristin Hannah', 'to-read', null, 'her'),
('The House in the Pines', 'Ana Reyes', 'to-read', null, 'her'),
('Romantic Comedy', 'Curtis Sittenfeld', 'to-read', null, 'her'),
('The House of Eve', 'Sadeqa Johnson', 'to-read', null, 'her'),
('Did You Hear About Kitty Karr?', 'Crystal Smith Paul', 'to-read', null, 'her'),
('Hidden Pictures', 'Jason Rekulak', 'read', 'Jul 13, 2025', 'her'),
('Book Lovers', 'Emily Henry', 'read', 'Feb 25, 2023', 'her'),
('The Maid', 'Nita Prose', 'to-read', null, 'her'),
('The Color of Magic', 'Terry Pratchett', 'to-read', null, 'her'),
('The Night Circus', 'Erin Morgenstern', 'to-read', null, 'her'),
('Lessons in Chemistry', 'Bonnie Garmus', 'read', null, 'her'),
('Great Expeditions', 'Alan Greenwood', 'read', 'Feb 26, 2023', 'her'),
('Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 'read', 'Jul 05, 2024', 'her'),
('The One Minute Manager', 'Kenneth H. Blanchard', 'to-read', null, 'her'),
('False Impression', 'Jeffrey Archer', 'read', null, 'her'),
('Rich Dad, Poor Dad', 'Robert T. Kiyosaki', 'read', null, 'her'),
('The Nanny', 'Melissa Nathan', 'read', 'Jan 06, 2023', 'her'),
('Eleanor Oliphant Is Completely Fine', 'Gail Honeyman', 'read', 'Jan 25, 2023', 'her'),
('A Good Girl''s Guide to Murder', 'Holly Jackson', 'read', 'Jul 25, 2023', 'her'),
('A Court of Thorns and Roses', 'Sarah J. Maas', 'to-read', null, 'her'),
('A Court of Mist and Fury', 'Sarah J. Maas', 'to-read', null, 'her'),
('The Song of Achilles', 'Madeline Miller', 'to-read', null, 'her'),
('The Invisible Life of Addie LaRue', 'V.E. Schwab', 'to-read', null, 'her'),
('Heartstopper: Volume One', 'Alice Oseman', 'to-read', null, 'her'),
('Heartstopper: Volume Two', 'Alice Oseman', 'to-read', null, 'her'),
('Heartstopper: Volume Three', 'Alice Oseman', 'to-read', null, 'her'),
('Heartstopper: Volume Four', 'Alice Oseman', 'to-read', null, 'her'),
('Reminders of Him', 'Colleen Hoover', 'to-read', null, 'her'),
('Crying in H Mart', 'Michelle Zauner', 'to-read', null, 'her'),
('Verity', 'Colleen Hoover', 'read', 'Jan 13, 2026', 'her'),
('It Happened One Summer', 'Tessa Bailey', 'to-read', null, 'her'),
('Hook, Line, and Sinker', 'Tessa Bailey', 'to-read', null, 'her'),
('It Ends with Us', 'Colleen Hoover', 'read', 'Apr 26, 2023', 'her'),
('I''m Glad My Mom Died', 'Jennette McCurdy', 'to-read', null, 'her'),
('Malibu Rising', 'Taylor Jenkins Reid', 'read', 'Aug 19, 2023', 'her'),
('Daisy Jones & The Six', 'Taylor Jenkins Reid', 'read', 'Mar 09, 2023', 'her'),
('The Love Hypothesis', 'Ali Hazelwood', 'read', 'Mar 04, 2023', 'her'),
('The Spider''s Palace and Other Stories', 'Richard Hughes', 'read', null, 'her'),
('The Midnight Library', 'Matt Haig', 'read', 'Dec 22, 2022', 'her'),
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'read', 'Dec 29, 2022', 'her'),
('The Final Gambit', 'Jennifer Lynn Barnes', 'to-read', null, 'her'),
('Loveless', 'Alice Oseman', 'to-read', null, 'her'),
('The Office BFFs', 'Jenna Fischer', 'to-read', null, 'her'),
('Yellowface', 'R.F. Kuang', 'read', 'Aug 16, 2023', 'her'),
('Carrie Soto Is Back', 'Taylor Jenkins Reid', 'read', 'Aug 17, 2025', 'her'),
('The Paris Apartment', 'Lucy Foley', 'to-read', null, 'her'),
('It Starts with Us', 'Colleen Hoover', 'read', 'Jun 14, 2023', 'her'),
('Animal Farm', 'George Orwell', 'to-read', null, 'her'),
('Never Lie', 'Freida McFadden', 'to-read', null, 'her'),
('When Only Love Remains', 'Durjoy Datta', 'read', null, 'her'),
('She Broke Up, I Didn''t!', 'Durjoy Datta', 'read', null, 'her'),
('Now That You''re Rich', 'Durjoy Datta', 'read', null, 'her'),
('Ohh Yes I am Single', 'Durjoy Datta', 'read', null, 'her'),
('You Were My Crush!', 'Durjoy Datta', 'read', null, 'her'),
('If It''s Not Forever. It''s Not Love.', 'Durjoy Datta', 'read', null, 'her'),
('Of Course I Love You!', 'Durjoy Datta', 'read', null, 'her'),
('Ravinder Singh Boxset', 'Ravinder Singh', 'read', null, 'her'),
('Making India Awesome', 'Chetan Bhagat', 'read', null, 'her'),
('What Young India Wants', 'Chetan Bhagat', 'read', null, 'her'),
('Half Girlfriend', 'Chetan Bhagat', 'read', null, 'her'),
('One Night at the Call Center', 'Chetan Bhagat', 'read', null, 'her'),
('Revolution 2020', 'Chetan Bhagat', 'read', null, 'her'),
('The 3 Mistakes of My Life', 'Chetan Bhagat', 'read', null, 'her'),
('Five Point Someone', 'Chetan Bhagat', 'read', null, 'her'),
('2 States: The Story of My Marriage', 'Chetan Bhagat', 'read', null, 'her'),
('Great Expectations', 'Charles Dickens', 'read', null, 'her'),
('Macbeth', 'William Shakespeare', 'read', null, 'her'),
('The Merchant of Venice', 'William Shakespeare', 'read', null, 'her'),
('Julius Caesar', 'William Shakespeare', 'read', null, 'her'),
('Midnight''s Children', 'Salman Rushdie', 'read', null, 'her'),
('The White Tiger', 'Aravind Adiga', 'read', null, 'her'),
('The God of Small Things', 'Arundhati Roy', 'read', null, 'her'),
('Madame Bovary', 'Gustave Flaubert', 'to-read', null, 'her'),
('Quichotte', 'Salman Rushdie', 'to-read', null, 'her');

-- Seed recommendations
insert into recommendations (title, author, user_id, sort_order) values
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'her', 0),
('Yellowface', 'R.F. Kuang', 'her', 1),
('None of This Is True', 'Lisa Jewell', 'her', 2);
