-- Seed his books (Audible + Kindle library)
-- Run this AFTER schema.sql in the Supabase SQL Editor

insert into books (title, author, shelf, date_read, user_id) values
('Then She Was Gone', 'Lisa Jewell', 'read', null, 'him'),
('The Prize: The Epic Quest for Oil, Money & Power', 'Daniel Yergin', 'read', null, 'him'),
('The Great Transformation', 'Chen Jian', 'read', null, 'him'),
('Babylon''s Ashes', 'James S.A. Corey', 'read', null, 'him'),
('1920: The Year of the Six Presidents', 'David Pietrusza', 'read', null, 'him'),
('Five Families: The Rise, Decline, and Resurgence of America''s Most Powerful Mafia Empires', 'Selwyn Raab', 'read', null, 'him'),
('Samsung Rising', 'Geoffrey Cain', 'read', null, 'him'),
('The War Below', 'Ernest Scheyder', 'read', null, 'him'),
('Embracing Defeat: Japan in the Wake of World War II', 'John W. Dower', 'read', null, 'him'),
('The Rise of Modern Japan', 'Mark J. Ravina', 'read', null, 'him'),
('Espionage and Covert Operations', 'Vejas Gabriel Liulevicius', 'read', null, 'him'),
('The Greek Revolution', 'Mark Mazower', 'read', null, 'him'),
('The Other Great Game', 'Sheila Miyoshi Jager', 'read', null, 'him'),
('Waking Giant: America in the Age of Jackson', 'David S. Reynolds', 'read', null, 'him'),
('Money Men: A Hot Startup, A Billion Dollar Fraud, A Fight for the Truth', 'Dan McCrum', 'read', null, 'him'),
('The Achilles Trap: Saddam Hussein, the C.I.A., and the Origins of America''s Invasion of Iraq', 'Steve Coll', 'read', null, 'him'),
('The Invention of Power', 'Bruce Bueno de Mesquita', 'read', null, 'him'),
('The Blazing World', 'Oliver Hembrough', 'read', null, 'him'),
('Tracers in the Dark: The Global Hunt for the Crime Lords of Cryptocurrency', 'Andy Greenberg', 'read', null, 'him'),
('The New Map: Energy, Climate, and the Clash of Nations', 'Daniel Yergin', 'read', null, 'him'),
('American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer', 'Kai Bird', 'read', null, 'him'),
('Fevre Dream', 'George R.R. Martin', 'read', null, 'him'),
('Follow the Pipelines', 'Charlotte Dennett', 'read', null, 'him'),
('Unscripted: The Epic Battle for a Media Empire', 'James B. Stewart', 'read', null, 'him'),
('The Wages of Destruction: The Making and Breaking of the Nazi Economy', 'Adam Tooze', 'read', null, 'him'),
('Butler to the World', 'Oliver Bullough', 'read', null, 'him'),
('Shutdown: How Covid Shook the World''s Economy', 'Adam Tooze', 'read', null, 'him'),
('The Right: The Hundred-Year War for American Conservatism', 'Matthew Continetti', 'read', null, 'him'),
('Rogues: True Stories of Grifters, Killers, Rebels and Crooks', 'Patrick Radden Keefe', 'read', null, 'him'),
('The WEIRDest People in the World', 'Joseph Henrich', 'read', null, 'him'),
('Chip War: The Quest for the World''s Most Critical Technology', 'Chris Miller', 'read', null, 'him'),
('The Great Ideas of Philosophy', 'Daniel N. Robinson', 'read', null, 'him'),
('From Jesus to Christianity', 'Bart D. Ehrman', 'read', null, 'him'),
('Slouching Towards Utopia: An Economic History of the Twentieth Century', 'J. Bradford DeLong', 'read', null, 'him'),
('Influence Empire: The Story of Tencent and China''s Tech Ambition', 'Lulu Yilun Chen', 'read', null, 'him'),
('The Machiavellians: Defenders of Freedom', 'James Burnham', 'read', null, 'him'),
('The Key Man: The True Story of How the Global Elite Was Duped by a Capitalist Fairy Tale', 'Simon Clark', 'read', null, 'him'),
('The Idea Factory: Bell Labs and the Great Age of American Innovation', 'Jon Gertner', 'read', null, 'him'),
('Project Hail Mary', 'Andy Weir', 'read', null, 'him'),
('Rothstein', 'David Pietrusza', 'read', null, 'him'),
('The Lords of Easy Money', 'Christopher Leonard', 'read', null, 'him'),
('The Writing Revolution', 'Judith C. Hochman', 'read', null, 'him'),
('Fur, Fortune, and Empire', 'Eric Jay Dolin', 'read', null, 'him'),
('The Rise of Andrew Jackson', 'David S. Heidler', 'read', null, 'him'),
('Gay New York', 'George Chauncey', 'read', null, 'him'),
('The Caesars Palace Coup', 'Max Frumes', 'read', null, 'him'),
('Iron Kingdom: The Rise and Downfall of Prussia', 'Christopher Clark', 'read', null, 'him'),
('The Firm: The Story of McKinsey and Its Secret Influence on American Business', 'Duff McDonald', 'read', null, 'him'),
('Den of Thieves', 'James B. Stewart', 'read', null, 'him'),
('Tomorrow, the World: The Birth of U.S. Global Supremacy', 'Stephen Wertheim', 'read', null, 'him'),
('Boom and Bust: A Global History of Financial Bubbles', 'William Quinn', 'read', null, 'him'),
('The Viking Heart', 'Arthur Herman', 'read', null, 'him'),
('Amazon Unbound', 'Brad Stone', 'read', null, 'him'),
('Zero Fail: The Rise and Fall of the Secret Service', 'Carol Leonnig', 'read', null, 'him'),
('Cynical Theories', 'Helen Pluckrose', 'read', null, 'him'),
('The Hobbit', 'J.R.R. Tolkien', 'read', null, 'him'),
('The Habsburgs: To Rule the World', 'Martyn Rady', 'read', null, 'him'),
('Managed by the Markets', 'Gerald F. Davis', 'read', null, 'him'),
('The Marshall Plan: Dawn of the Cold War', 'Benn Steil', 'read', null, 'him'),
('The Rise of American Democracy', 'Sean Wilentz', 'read', null, 'him'),
('King Leopold''s Ghost', 'Adam Hochschild', 'read', null, 'him'),
('Crucible: The Long End of the Great War', 'Charles Emmerson', 'read', null, 'him'),
('The Eastern Orthodox Church: A New History', 'John Anthony McGuckin', 'read', null, 'him'),
('Tech Titans of China', 'Rebecca A. Fannin', 'read', null, 'him'),
('Say Nothing: A True Story of Murder and Memory in Northern Ireland', 'Patrick Radden Keefe', 'read', null, 'him'),
('The Innovation Stack', 'Jim McKelvey', 'read', null, 'him'),
('Who Dares Wins', 'Dominic Sandbrook', 'read', null, 'him'),
('Bismarck: The Man and the Statesman', 'A.J.P. Taylor', 'read', null, 'him'),
('The Secret Sentry', 'Matthew Aid', 'read', null, 'him'),
('1917: Lenin, Wilson, and the Birth of the New World Disorder', 'Arthur Herman', 'read', null, 'him'),
('The Great Reversal: How America Gave Up on Free Markets', 'Thomas Philippon', 'read', null, 'him'),
('Black Wave: Saudi Arabia, Iran, and the Forty-Year Rivalry', 'Kim Ghattas', 'read', null, 'him'),
('Erdogan Rising', 'Hannah Lucinda Smith', 'read', null, 'him'),
('The Warehouse', 'Rob Hart', 'read', null, 'him'),
('Indian Horse', 'Richard Wagamese', 'read', null, 'him'),
('The Road Taken', 'Henry Petroski', 'read', null, 'him'),
('American Revolutions: A Continental History', 'Alan Taylor', 'read', null, 'him'),
('Fentanyl, Inc.: How Rogue Chemists Are Creating the Deadliest Wave of the Opioid Epidemic', 'Ben Westhoff', 'read', null, 'him'),
('The People''s Tycoon: Henry Ford and the American Century', 'Steven Watts', 'read', null, 'him'),
('Kickback: Exposing the Global Corporate Bribery Network', 'David Montero', 'read', null, 'him'),
('Surprise, Kill, Vanish', 'Annie Jacobsen', 'read', null, 'him'),
('The Poison Squad', 'Deborah Blum', 'read', null, 'him'),
('The Undercover Economist', 'Tim Harford', 'read', null, 'him'),
('AI Superpowers: China, Silicon Valley, and the New World Order', 'Kai-Fu Lee', 'read', null, 'him'),
('Napoleon: A Life', 'Adam Zamoyski', 'read', null, 'him'),
('The Making of Modern Economics', 'Mark Skousen', 'read', null, 'him'),
('The Great Game: The Struggle for Empire in Central Asia', 'Peter Hopkirk', 'read', null, 'him'),
('Genghis Khan and the Making of the Modern World', 'Jack Weatherford', 'read', null, 'him'),
('The Patch: The People, Pipelines, and Politics of the Oil Sands', 'Chris Turner', 'read', null, 'him'),
('Saudi, Inc.: The Arabian Kingdom''s Pursuit of Profit and Power', 'Ellen R. Wald', 'read', null, 'him'),
('Pale Horse Rider', 'Mark Jacobson', 'read', null, 'him'),
('Conspiracy: A True Story of Power, Sex, and a Billionaire''s Secret Plot', 'Ryan Holiday', 'read', null, 'him'),
('Heretics and Believers: A History of the English Reformation', 'Peter Marshall', 'read', null, 'him'),
('Behold, America', 'Sarah Churchwell', 'read', null, 'him'),
('The Curse of Bigness: Antitrust in the New Gilded Age', 'Tim Wu', 'read', null, 'him'),
('The Chickenshit Club', 'Jesse Eisinger', 'read', null, 'him'),
('Bad Blood: Secrets and Lies in a Silicon Valley Startup', 'John Carreyrou', 'read', null, 'him'),
('Billion Dollar Whale', 'Bradley Hope', 'read', null, 'him'),
('The Age of Eisenhower', 'William I. Hitchcock', 'read', null, 'him'),
('The Perfectionists: How Precision Engineers Created the Modern World', 'Simon Winchester', 'read', null, 'him'),
('Conservatism: An Invitation to the Great Tradition', 'Roger Scruton', 'read', null, 'him'),
('Blitzed: Drugs in the Third Reich', 'Norman Ohler', 'read', null, 'him'),
('The Pope and Mussolini', 'David I. Kertzer', 'read', null, 'him'),
('Barbarians at the Gate: The Fall of RJR Nabisco', 'Bryan Burrough', 'read', null, 'him'),
('We the Corporations', 'Adam Winkler', 'read', null, 'him'),
('The Master Switch: The Rise and Fall of Information Empires', 'Tim Wu', 'read', null, 'him'),
('Under the Banner of Heaven', 'Jon Krakauer', 'read', null, 'him'),
('Antifragile: Things That Gain from Disorder', 'Nassim Nicholas Taleb', 'read', null, 'him'),
('59 Seconds: Think a Little, Change a Lot', 'Richard Wiseman', 'read', null, 'him'),
('Fractured Continent: Europe''s Crises and the Fate of the West', 'William Drozdiak', 'read', null, 'him'),
('God Save Texas', 'Lawrence Wright', 'read', null, 'him'),
('The General vs. the President', 'H.W. Brands', 'read', null, 'him'),
('The Man from the Train', 'Bill James', 'read', null, 'him'),
('Lost to the West: The Forgotten Byzantine Empire', 'Lars Brownworth', 'read', null, 'him'),
('Brigham Young: Pioneer Prophet', 'John G. Turner', 'read', null, 'him'),
('Zealot: The Life and Times of Jesus of Nazareth', 'Reza Aslan', 'read', null, 'him'),
('The Future Is History: How Totalitarianism Reclaimed Russia', 'Masha Gessen', 'read', null, 'him'),
('Capitalism: A Global History', 'Sven Beckert', 'read', null, 'him'),
('Out of Hitler''s Shadow', 'Tobias Straumann', 'read', null, 'him'),
('Barons: Money, Power, and the Corruption of America''s Food Industry', 'Austin Frerick', 'read', null, 'him'),
('The Corporate Lifecycle', 'Aswath Damodaran', 'read', null, 'him'),
('Global Capitalism: Its Fall and Rise in the Twentieth Century', 'Jeffry A. Frieden', 'read', null, 'him'),
('Waste Wars', 'Alexander Clapp', 'read', null, 'him'),
('A Modern Economic History of Japan', 'Russell Jones', 'read', null, 'him'),
('Apple in China', 'Patrick McGee', 'read', null, 'him'),
('These Are the Plunderers', 'Gretchen Morgenson', 'read', null, 'him'),
('The Thinking Machine', 'Stephen Witt', 'read', null, 'him'),
('The Nvidia Way', 'Tae Kim', 'read', null, 'him'),
('More Money Than God: Hedge Funds and the Making of a New Elite', 'Sebastian Mallaby', 'read', null, 'him'),
('House of Huawei', 'Eva Dou', 'read', null, 'him'),
('Zero Sum: The Arc of International Business in Russia', 'Charles Hecker', 'read', null, 'him'),
('Global Development: A Cold War History', 'Sara Lorenzini', 'read', null, 'him'),
('Lords of Strategy', 'Walter Kiechel', 'read', null, 'him'),
('The Big Fail', 'Joe Nocera', 'read', null, 'him'),
('A Brief History of Central Banking', 'Dominic Haynes', 'read', null, 'him'),
('The Corporation and the Twentieth Century', 'Richard N. Langlois', 'read', null, 'him'),
('The Deal of the Century: The Breakup of AT&T', 'Steve Coll', 'read', null, 'him'),
('Globalists: The End of Empire and the Birth of Neoliberalism', 'Quinn Slobodian', 'read', null, 'him'),
('The Nobel Family', 'Bengt Jangfeldt', 'read', null, 'him'),
('The Taking of Getty Oil', 'Steve Coll', 'read', null, 'him'),
('Kicking Away the Ladder', 'Ha-Joon Chang', 'read', null, 'him'),
('The Price of Time: The Real Story of Interest', 'Edward Chancellor', 'read', null, 'him'),
('The Rise and Fall of the Neoliberal Order', 'Gary Gerstle', 'read', null, 'him'),
('Oceans of Grain', 'Scott Reynolds Nelson', 'read', null, 'him'),
('A New Way to Think', 'Roger L. Martin', 'read', null, 'him'),
('The Devil''s Playbook', 'Lauren Etter', 'read', null, 'him'),
('The Rare Metals War', 'Guillaume Pitron', 'read', null, 'him'),
('Ages of American Capitalism', 'Jonathan Levy', 'read', null, 'him'),
('How Asia Works', 'Joe Studwell', 'read', null, 'him'),
('Prophets of Regulation', 'Thomas K. McCraw', 'read', null, 'him'),
('The World for Sale', 'Javier Blas', 'read', null, 'him'),
('Three Days at Camp David', 'Jeffrey E. Garten', 'read', null, 'him'),
('The Secret Life of Groceries', 'Benjamin Lorr', 'read', null, 'him'),
('Religion and the Rise of Capitalism', 'Benjamin M. Friedman', 'read', null, 'him'),
('The Money Hackers', 'Daniel P. Simon', 'read', null, 'him'),
('Broker, Trader, Lawyer, Spy', 'Eamon Javers', 'read', null, 'him'),
('The Commanding Heights', 'Daniel Yergin', 'read', null, 'him'),
('Red Capitalism: The Fragile Financial Foundation of China''s Extraordinary Rise', 'Carl Walter', 'read', null, 'him'),
('Big Business: A Love Letter to an American Anti-Hero', 'Tyler Cowen', 'read', null, 'him'),
('Railroader: The Unfiltered Genius and Controversy of Four-Time CEO Hunter Harrison', 'Howard Green', 'read', null, 'him');
